"""Add scheduled_for and sent_at to notifications

Revision ID: 20fcf890e9d4
Revises: ff9cee65dc59
Create Date: 2025-09-05 17:56:13.162414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20fcf890e9d4'
down_revision = 'ff9cee65dc59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_notifications_scheduled_for'), 'notifications', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_notifications_sent_at'), 'notifications', ['sent_at'], unique=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_notifications_sent_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_scheduled_for'), table_name='notifications')
    op.drop_column('notifications', 'sent_at')
    op.drop_column('notifications', 'scheduled_for')
    # ### end Alembic commands ###