"""add_booking_status_history_table

Revision ID: 94ba2ea7fff5
Revises: ef970acfa96f
Create Date: 2025-08-31 19:17:38.723963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ba2ea7fff5'
down_revision = 'ef970acfa96f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.Enum('PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='bookingstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='bookingstatus'), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_booking_status_history_booking_created', 'booking_status_history', ['booking_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_booking_status_history_booking_id'), 'booking_status_history', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_status_history_changed_by'), 'booking_status_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_booking_status_history_created_at'), 'booking_status_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_booking_status_history_id'), 'booking_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_booking_status_history_new_status'), 'booking_status_history', ['new_status'], unique=False)
    op.create_index(op.f('ix_booking_status_history_old_status'), 'booking_status_history', ['old_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_status_history_old_status'), table_name='booking_status_history')
    op.drop_index(op.f('ix_booking_status_history_new_status'), table_name='booking_status_history')
    op.drop_index(op.f('ix_booking_status_history_id'), table_name='booking_status_history')
    op.drop_index(op.f('ix_booking_status_history_created_at'), table_name='booking_status_history')
    op.drop_index(op.f('ix_booking_status_history_changed_by'), table_name='booking_status_history')
    op.drop_index(op.f('ix_booking_status_history_booking_id'), table_name='booking_status_history')
    op.drop_index('idx_booking_status_history_booking_created', table_name='booking_status_history')
    op.drop_table('booking_status_history')
    # ### end Alembic commands ###