"""Add payment system tables

Revision ID: ef970acfa96f
Revises: 09b4a29ad986
Create Date: 2025-08-31 19:04:46.685720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef970acfa96f'
down_revision = '09b4a29ad986'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('STRIPE', 'PAYPAL', name='paymentmethod'), nullable=False),
    sa.Column('stripe_transfer_id', sa.String(), nullable=True),
    sa.Column('paypal_payout_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='withdrawalstatus'), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('payout_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_worker_payouts_status_requested', 'worker_payouts', ['status', 'requested_at'], unique=False)
    op.create_index(op.f('ix_worker_payouts_id'), 'worker_payouts', ['id'], unique=False)
    op.create_index(op.f('ix_worker_payouts_payment_method'), 'worker_payouts', ['payment_method'], unique=False)
    op.create_index(op.f('ix_worker_payouts_paypal_payout_id'), 'worker_payouts', ['paypal_payout_id'], unique=False)
    op.create_index(op.f('ix_worker_payouts_requested_at'), 'worker_payouts', ['requested_at'], unique=False)
    op.create_index(op.f('ix_worker_payouts_status'), 'worker_payouts', ['status'], unique=False)
    op.create_index(op.f('ix_worker_payouts_stripe_transfer_id'), 'worker_payouts', ['stripe_transfer_id'], unique=False)
    op.create_index(op.f('ix_worker_payouts_worker_id'), 'worker_payouts', ['worker_id'], unique=False)
    op.create_table('payment_disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('initiated_by', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'CLOSED', name='disputestatus'), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_disputes_status_created', 'payment_disputes', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_payment_disputes_created_at'), 'payment_disputes', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_disputes_id'), 'payment_disputes', ['id'], unique=False)
    op.create_index(op.f('ix_payment_disputes_initiated_by'), 'payment_disputes', ['initiated_by'], unique=False)
    op.create_index(op.f('ix_payment_disputes_payment_id'), 'payment_disputes', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_disputes_resolved_by'), 'payment_disputes', ['resolved_by'], unique=False)
    op.create_index(op.f('ix_payment_disputes_status'), 'payment_disputes', ['status'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('payout_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['payout_id'], ['worker_payouts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_transactions_user_type', 'payment_transactions', ['user_id', 'transaction_type'], unique=False)
    op.create_index(op.f('ix_payment_transactions_created_at'), 'payment_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_transactions_id'), 'payment_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_payment_id'), 'payment_transactions', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_payout_id'), 'payment_transactions', ['payout_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_reference_id'), 'payment_transactions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_transaction_type'), 'payment_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_payment_transactions_user_id'), 'payment_transactions', ['user_id'], unique=False)
    op.add_column('payments', sa.Column('worker_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('payments', sa.Column('payment_method', sa.Enum('STRIPE', 'PAYPAL', name='paymentmethod'), nullable=False))
    op.add_column('payments', sa.Column('paypal_payment_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('held_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('refund_reason', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('payment_metadata', sa.JSON(), nullable=True))
    op.create_index('idx_payments_method_status', 'payments', ['payment_method', 'status'], unique=False)
    op.create_index(op.f('ix_payments_payment_method'), 'payments', ['payment_method'], unique=False)
    op.create_index(op.f('ix_payments_paypal_payment_id'), 'payments', ['paypal_payment_id'], unique=False)
    # Skip ALTER COLUMN for SQLite compatibility - password_hash is already nullable
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip ALTER COLUMN for SQLite compatibility
    op.drop_index(op.f('ix_payments_paypal_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_method'), table_name='payments')
    op.drop_index('idx_payments_method_status', table_name='payments')
    op.drop_column('payments', 'payment_metadata')
    op.drop_column('payments', 'refund_reason')
    op.drop_column('payments', 'refunded_at')
    op.drop_column('payments', 'held_at')
    op.drop_column('payments', 'paypal_payment_id')
    op.drop_column('payments', 'payment_method')
    op.drop_column('payments', 'worker_amount')
    op.drop_index(op.f('ix_payment_transactions_user_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_transaction_type'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_reference_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_payout_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_payment_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_created_at'), table_name='payment_transactions')
    op.drop_index('idx_payment_transactions_user_type', table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_payment_disputes_status'), table_name='payment_disputes')
    op.drop_index(op.f('ix_payment_disputes_resolved_by'), table_name='payment_disputes')
    op.drop_index(op.f('ix_payment_disputes_payment_id'), table_name='payment_disputes')
    op.drop_index(op.f('ix_payment_disputes_initiated_by'), table_name='payment_disputes')
    op.drop_index(op.f('ix_payment_disputes_id'), table_name='payment_disputes')
    op.drop_index(op.f('ix_payment_disputes_created_at'), table_name='payment_disputes')
    op.drop_index('idx_payment_disputes_status_created', table_name='payment_disputes')
    op.drop_table('payment_disputes')
    op.drop_index(op.f('ix_worker_payouts_worker_id'), table_name='worker_payouts')
    op.drop_index(op.f('ix_worker_payouts_stripe_transfer_id'), table_name='worker_payouts')
    op.drop_index(op.f('ix_worker_payouts_status'), table_name='worker_payouts')
    op.drop_index(op.f('ix_worker_payouts_requested_at'), table_name='worker_payouts')
    op.drop_index(op.f('ix_worker_payouts_paypal_payout_id'), table_name='worker_payouts')
    op.drop_index(op.f('ix_worker_payouts_payment_method'), table_name='worker_payouts')
    op.drop_index(op.f('ix_worker_payouts_id'), table_name='worker_payouts')
    op.drop_index('idx_worker_payouts_status_requested', table_name='worker_payouts')
    op.drop_table('worker_payouts')
    # ### end Alembic commands ###